---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    k8s-app: prometheus-operator
---
# expose Prometheus instance to public
apiVersion: v1
kind: Service
metadata:
  name: prometheus-public
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30999
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
