dist: trusty
sudo: false
language: go
cache:
  directories:
  - "$GOPATH/pkg/dep"
go:
- 1.11.1
os:
- linux
env:
  global:
  - DEP_VERSION=v0.5.0
  - BAZEL_VERSION=0.18.0
  - KUBECTL_VERSION=v1.10.0
  # DOCKER_USERNAME and DOCKER_PASSWORD
  - secure: WPg9MOQRmlRaaas8nrGwaPgmI+JVe14WOjMY0VOelsGKK7bfeo4Ol6anndPsh28jWhW7IXm5vzwoMikikHFaVQFL0yE15eQkrnnSVKOfs1Q40gFO67et/Bj4SXMQXyfkt82o7BUXjQLW53RLCDm68hPm6eCORtZaqzoQKjJhBJR1LZt/SfOsVfbMYzfFKZ6ZQ6nXbrtxnm4+MCz3B97Zd93lEMJPAFjLcCfsGcTPJMYza2alYBdyOU8rNn4bMGpEzLLzRbI384rrAHgscjgizVn19F+72Zgy7/R/M6HPq+cmJEaUwgWkodref07CNXCboORDl1e7pw1ZlnnarytRJUWNlCWMPlvY/bTaH2OwKRZ+wn5dwxmQU15FGF7txdynA6/8QLJM20ba4ALkFymODBnGfQRI+Qy55qIXCMER29/OqC0XNbBZnPiQa+LpftrX8TINlaJlhoXpvTneE+sX+0K13/NFs0bVlIrG27mdsaeIEeFKV9WbxJrmkSF1IDbQbqDd2jJBxg7idTZDzAJU4aI7mqVydH569ati+RtMFIxSh6iHu3j0vZPo+mKL6tzAWoFlEh21Q4nMkzsRlIdNh9kjC3tVzn3iaucxxZIYDU43wtMcELjZY/q1gzfl73VXd3yrJFRzw5E/J4KOlQnqBOj2x5IMIiSOsRJTJUqiXVk=
  - secure: DoOpQMuWciooVu4R095mQ3jtqv2sK6fbDRMx6C6LfkOWeTei+qLse+CY0tU77GhRD0vmsa8b2b6O9w5Pieu0gK4RssyTF6Tjyh8pOonQzP5DIQqEqmLZHAr4VuDGF4ZRwODA7NogHltrklg7fFwTvvDcIl1ITUC89HlBphO12CDAe6S0nMT/+tIgxAzFKcdsYJs0/SiSDI/JvdS+pfM1U8SmjfemazV1kjAA342MFsKO6tubWTyCxlTFGEb6j6/z6heylrKCkJC+gTG+PQY5idrFZhM77NmH1lT1mAbNVdEjsIWFRJYJysElTw9/ezMaHvQ/0IkfTkkxCYaETYJrXk88Ce3qz0lpoJG3GW9Dxg/ShP//PdotduvX7V0fQthWO433tvMTPBBiG+2ptBUz5RWBs2sMBLlwYijyHgk2uNWeaHbc40JlmliK09jz1mqvglyWlISF74puMubiuY8SnoOqPznIgyp4VIDA1sWqgLqyKccYUQgc4TSoZA6on72izcVWHKEPcjdBktVzrZK8DtH/rMfyBrMS2qJ4f9YAD81693fIMg1D2b9y8nDafvavBb5r+DGoLvNqCxhBh9bixKX6ES+XmOZSazO41dO+Xyk85MYwNSCPc9pofeYFEd6r0e5v31OV2W8mU9ANpKokOrfAfXGdIV3+p2TaTyRijo8=
before_install:
- |
  curl -Lo dep "https://github.com/golang/dep/releases/download/${DEP_VERSION}/dep-linux-amd64"
  chmod +x dep
  sudo mv dep /usr/local/bin/
- |
  curl -Lo install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
  chmod +x install.sh
  ./install.sh --user
  rm -f install.sh
  mv .bazelrc.travis .bazelrc
install:
- make setup
script:
- make update-bazel
- make verify
# - make test-ci
- make docker-kanarini
# - make check
after_success:
- if [ "$TRAVIS_OS_NAME" == "linux" -a ! -z "$TRAVIS_TAG" ]; then echo "Executing
  release on tag build $TRAVIS_TAG"; docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  make release-kanarini; else echo "Not executing release on non-tag build"; fi
