---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: emoji
  namespace: kanarini-demo
  labels:
    prometheus: default
spec:
  groups:
  - name: example-rules
    rules:
    - expr: |
        rate(request_count{result="failure"}[1m]) / ignoring(result) rate(request_count_total[1m])
      record: failure_rate_1m
