---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: emoji
  namespace: kanarini-demo
  labels:
    prometheus: default
spec:
  groups:
  - name: example-rules
    interval: 1s
    rules:
    - expr: |
        sum(increase(request_count{result="failure"}[1m])) by (service,job,namespace) / sum(increase(request_count_total[1m])) by (service,job,namespace)
      record: failure_by_service_1m
