---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: emoji
  namespace: kanarini-demo
  labels:
    prometheus: default
spec:
  groups:
  - name: example-rules
    rules:
    - expr: |
        increase(request_count{result="failure"}[1m])
      record: request_count:failed
    - expr: |
        increase(request_count{result="success"}[1m])
      record: request_count:succeeded
    - expr: |
        increase(request_count_total[1m])
      record: request_count:total
    - expr: |
        sum(request_count:failed) by (service)
      record: request_count:failed:by_service
    - expr: |
        sum(request_count:succeeded) by (service)
      record: request_count:succeeded:by_service
    - expr: |
        sum(request_count:total) by (service)
      record: request_count:total:by_service
    - expr: |
        rate(request_count{result="failure"}[1m]) / ignoring(result) rate(request_count_total[1m])
      record: request_count:failure:rate1m
