---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: default
  name: emoji
  namespace: kanarini-demo
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: emoji
