---
kind: Service
apiVersion: v1
metadata:
  name: v1
  namespace: kanarini-manual
  labels:
    app: manual
spec:
  selector:
    app: manual
    version: v1
  ports:
  - name: port-1
    nodePort: 30911
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    nodePort: 30921
    port: 9090
    protocol: TCP
    targetPort: 9090
  sessionAffinity: None
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: v2
  namespace: kanarini-manual
  labels:
    app: manual
spec:
  selector:
    app: manual
    version: v2
  ports:
  - name: port-1
    nodePort: 30912
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    nodePort: 30922
    port: 9090
    protocol: TCP
    targetPort: 9090
  sessionAffinity: None
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: v3
  namespace: kanarini-manual
  labels:
    app: manual
spec:
  selector:
    app: manual
    version: v3
  ports:
  - name: port-1
    nodePort: 30913
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-2
    nodePort: 30923
    port: 9090
    protocol: TCP
    targetPort: 9090
  sessionAffinity: None
  type: NodePort
