---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-canary
  namespace: example-manual
  labels:
    app: example
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      track: canary
  template:
    metadata:
      labels:
        app: example
        track: canary
    spec:
      containers:
      - name: example
        image: nilebox/kanarini-example:0.0.0-140b856
        args:
        - --error-rate
        - "1.0"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-stable
  namespace: example-manual
  labels:
    app: example
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      track: stable
  template:
    metadata:
      labels:
        app: example
        track: stable
    spec:
      containers:
      - name: example
        image: nilebox/kanarini-example:0.0.0-140b856
        args:
        - --error-rate
        - "0.0"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
