---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  namespace: example-manual
  labels:
    prometheus: default
spec:
  groups:
  - name: example-rules
    rules:
    - expr: |
        rate(request_count{result="failure"}[5m]) / ignoring(result) rate(request_count_total[5m])
      record: request_count:failure:rate5m
