---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: example
  name: prometheus-example
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-example
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-example
subjects:
- kind: ServiceAccount
  name: prometheus-example
  namespace: example
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-example
  namespace: example
spec:
  serviceAccountName: prometheus-example
  serviceMonitorSelector:
    matchLabels:
      app: example
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: example
  name: prometheus-example
  namespace: example
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: example
---
# expose to public
apiVersion: v1
kind: Service
metadata:
  name: prometheus-public
  namespace: example
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-example
