---
apiVersion: v1
kind: Namespace
metadata:
  name: heptio-contour
---
kind: Namespace
apiVersion: v1
metadata:
  name: kanarini-example
  labels:
      monitored: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
