---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  # baseImage: nilebox/prometheus
  # tag: request-logging-5
  logLevel: debug
  scrapeInterval: 5s
  evaluationInterval: 5s
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitored: "true"
  serviceMonitorSelector:
    matchLabels:
      prometheus: default
  ruleNamespaceSelector:
    matchLabels:
      monitored: "true"
  ruleSelector:
    matchLabels:
      prometheus: default
  resources:
    requests:
      memory: 400Mi
