---
apiVersion: v1
kind: Service
metadata:
 name: contour
 namespace: heptio-contour
spec:
  # Here we use NodePort instead of LoadBalancer.
  # This is only suitable for the demo running on local machine (minikube/kind)!
  # In production LoadBalancer should be used instead.
  # See https://github.com/heptio/contour/blob/master/deployment/common/service.yaml
  selector:
    app: contour
  ports:
  - name: http
    nodePort: 30900
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30943
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: NodePort
