---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: example
  name: prometheus-example
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: example
