---
# expose to public
apiVersion: v1
kind: Service
metadata:
  name: prometheus-public
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-example
